# Generated by Django 4.2.2 on 2023-08-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
